name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: checkout da code

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build and Push Kali to dockerhub
      with:
        image: akacodemonkey/kali
        tags: latest
        labels: maintainer=akacodemonkey
        dockerfile: Dockerfile.yml
        push: true
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        repository: docker.io
        tag_with_ref: true
