name: Docker Image CI

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build-Push Kali to dockerhub
      uses: docker/build-push-action@v1
      with:
        context: .
        dockerfile: DockerFile.yml
        push: true
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        repository: akacodemonkey/kali
        tag_with_ref: true
